# Content-Based Filtering

## Read data

In [33]:
import pandas as pd
movies = pd.read_csv("movies_data/movies.csv", sep=",")
movies

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",1992-09-04,2040920,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238
4799,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],[],2011-12-26,0,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5
4800,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-10-13,0,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6
4801,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-05-03,0,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7
4802,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2005-08-05,0,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16

In [34]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(stop_words='english')
movies["overview"] = movies["overview"].fillna("") # Filling NaNs with empty string
tfidf_matrix = tfidf.fit_transform(movies["overview"])
pd.DataFrame(tfidf_matrix.toarray(), columns=tfidf.get_feature_names_out())

,00,000,007,07am,10,100,1000,101,108,10th,...,zuckerberg,zula,zuzu,zyklon,Ã¦on,Ã©loigne,Ã©migrÃ©,Ã©tÃ©,Ãºnica,Ã¼ber
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4799,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4800,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4801,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4802,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### Similarity Matrix

In [35]:
from sklearn.metrics.pairwise import linear_kernel
similarity_matrix = linear_kernel(tfidf_matrix, tfidf_matrix)
similarity_matrix

array([[1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 0.02160533, 0.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.01488159, 0.        ,
        0.        ],
       ...,
       [0.        , 0.02160533, 0.01488159, ..., 1.        , 0.01609091,
        0.00701914],
       [0.        , 0.        , 0.        , ..., 0.01609091, 1.        ,
        0.01171696],
       [0.        , 0.        , 0.        , ..., 0.00701914, 0.01171696,
        1.        ]])

### Find the most similar movies to the certain movie

In [38]:
def similar_movies(movie_title: str, nr_movies: int) -> pd.DataFrame:
    # Get the index of the movie by its title
    movie_index = movies.loc[movies["title"] == movie_title].index[0]
    # Get the similarity scores of the movie with all other movies (including itself)
    # and enumerate them to keep track of the index
    scores = list(enumerate(similarity_matrix[movie_index].tolist()))
    # Remove the movie itself from the list (it will have a similarity score of 1)
    scores.pop(movie_index)
    # Sort the movies by similarity score in descending order
    scores.sort(reverse=True, key=lambda x: x[1])
    # Get the top n movies
    scores= scores[:nr_movies]
    return pd.DataFrame([movies.iloc[score[0]] for score in scores])

sm = similar_movies("Pulp Fiction", 10)
sm

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
3526,5500000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 80, ""nam...",NaN,9277,"[{""id"": 520, ""name"": ""chicago""}, {""id"": 622, ""...",en,The Sting,Set in the 1930's this intricate caper deals w...,28.500913,"[{""name"": ""Universal Pictures"", ""id"": 33}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",1973-12-25,159616327,129.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,...all it takes is a little confidence.,The Sting,7.9,622
3194,9000000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",NaN,12454,[],en,All or Nothing,"Penny's love for her partner, taxi-driver Phil...",2.872281,"[{""name"": ""Les Films Alain Sarde"", ""id"": 635},...","[{""iso_3166_1"": ""FR"", ""name"": ""France""}, {""iso...",2002-05-17,0,128.0,"[{""iso_639_1"": ""ar"", ""name"": ""\u0627\u0644\u06...",Released,NaN,All or Nothing,7.0,33
3466,6000000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",NaN,10215,"[{""id"": 848, ""name"": ""double life""}, {""id"": 10...",en,Sliding Doors,"Gwyneth Paltrow plays London publicist Helen, ...",15.639016,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",1998-04-23,58000000,99.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,What if one split second sent your life in two...,Sliding Doors,6.5,354
4624,0,"[{""id"": 27, ""name"": ""Horror""}, {""id"": 18, ""nam...",http://www.locker13.com/,250184,"[{""id"": 321, ""name"": ""terror""}, {""id"": 9706, ""...",en,Locker 13,"The story of Skip, a young ex-convict who take...",1.905197,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2014-03-29,0,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,Locker 13,6.8,3
2917,25000000,"[{""id"": 18, ""name"": ""Drama""}]",http://www.thefightermovie.com,45317,"[{""id"": 6075, ""name"": ""sport""}, {""id"": 154123,...",en,The Fighter,"The Fighter, is a drama about boxer ""Irish"" Mi...",31.019381,"[{""name"": ""Paramount Pictures"", ""id"": 4}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2010-12-17,93617009,116.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Every dream deserves a fighting chance.,The Fighter,7.2,1486
4036,35000000,"[{""id"": 27, ""name"": ""Horror""}]",NaN,332285,"[{""id"": 726, ""name"": ""drug abuse""}, {""id"": 170...",en,Antibirth,In a desolate community full of drug-addled Ma...,3.674294,"[{""name"": ""Hideaway Pictures"", ""id"": 20068}, {...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2016-09-02,0,94.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,Antibirth,4.8,40
3491,6000000,"[{""id"": 18, ""name"": ""Drama""}]",http://www.sonyclassics.com/thewackness/,13990,"[{""id"": 10683, ""name"": ""coming of age""}, {""id""...",en,The Wackness,"Set in New York City in the sweltering summer,...",7.161051,"[{""name"": ""SBK Pictures"", ""id"": 11665}, {""name...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2008-07-03,2899975,99.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,The Wackness,6.2,94
2849,12000000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 12, ""name...",NaN,129670,"[{""id"": 680, ""name"": ""montana""}, {""id"": 1415, ...",en,Nebraska,"An aging, booze-addled father takes a trip fro...",29.223881,"[{""name"": ""Paramount Vantage"", ""id"": 838}, {""n...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-09-21,17654912,115.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Life's not about winning or losing. It's about...,Nebraska,7.4,636
3504,6000000,"[{""id"": 80, ""name"": ""Crime""}, {""id"": 18, ""name...",NaN,9282,"[{""id"": 567, ""name"": ""alcohol""}, {""id"": 572, ""...",en,11:14,Tells the seemingly random yet vitally connect...,15.048067,"[{""name"": ""Firm Films"", ""id"": 1838}, {""name"": ...","[{""iso_3166_1"": ""CA"", ""name"": ""Canada""}, {""iso...",2003-05-16,0,86.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Fate can change in seconds.,11:14,6.8,206
3346,6600000,"[{""id"": 35, ""name"": ""Comedy""}]",http://www.jumpingthebroom-movie.com/,57119,"[{""id"": 12532, ""name"": ""african american""}, {""...",en,Jumping the Broom,Two very different families converge on Martha...,4.492455,"[{""name"": ""TriStar Pictures"", ""id"": 559}, {""na...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2011-05-06,37710610,112.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Sometimes the only way to get past family dram...,Jumping the Broom,6.0,56